# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'score_statistics.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import json
import os
import csv


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1410, 836)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 130, 1391, 501))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(1, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(2, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(2, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(2, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(3, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(3, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(3, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(4, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(4, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(4, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(5, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(5, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(5, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(5, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(6, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(6, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(6, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(6, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(7, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(7, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(7, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(7, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(8, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(8, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(8, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(8, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(9, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(9, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(9, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(9, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(9, 9, item)
        self.textEditName = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditName.setGeometry(QtCore.QRect(110, 70, 131, 41))
        self.textEditName.setObjectName("textEditName")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(50, 70, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEditAddr = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditAddr.setGeometry(QtCore.QRect(320, 70, 131, 41))
        self.textEditAddr.setObjectName("textEditAddr")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(260, 70, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(640, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_query = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_query.setGeometry(QtCore.QRect(750, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_query.setFont(font)
        self.pushButton_query.setObjectName("pushButton_query")
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(860, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_export = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_export.setGeometry(QtCore.QRect(980, 700, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_export.setFont(font)
        self.pushButton_export.setObjectName("pushButton_export")
        self.pushButton_inport = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_inport.setGeometry(QtCore.QRect(970, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_inport.setFont(font)
        self.pushButton_inport.setObjectName("pushButton_inport")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1081, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_add.clicked.connect(self.add_name_score)
        self.pushButton_query.clicked.connect(self.query_name_score)
        self.pushButton_delete.clicked.connect(self.delete_name_score)
        # self.pushButton_inport.clicked.connect(MainWindow.close)
        self.pushButton_export.clicked.connect(self.export_data)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "一"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "二"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "三"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "四"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "五"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "六"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "七"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "八"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "九"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "十"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "题号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "答案"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "题号"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "答案"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "题号"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "答案"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "题号"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "答案"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "题号"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "答案"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "21"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("MainWindow", "31(R5)"))
        item = self.tableWidget.item(0, 8)
        item.setText(_translate("MainWindow", "41(R32)"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("MainWindow", "22"))
        item = self.tableWidget.item(1, 6)
        item.setText(_translate("MainWindow", "32(R7)"))
        item = self.tableWidget.item(1, 8)
        item.setText(_translate("MainWindow", "42(R33)"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("MainWindow", "23"))
        item = self.tableWidget.item(2, 6)
        item.setText(_translate("MainWindow", "33(R9)"))
        item = self.tableWidget.item(2, 8)
        item.setText(_translate("MainWindow", "43(R34)"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("MainWindow", "24"))
        item = self.tableWidget.item(3, 6)
        item.setText(_translate("MainWindow", "34(R12)"))
        item = self.tableWidget.item(3, 8)
        item.setText(_translate("MainWindow", "44(R35)"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("MainWindow", "25"))
        item = self.tableWidget.item(4, 6)
        item.setText(_translate("MainWindow", "35(R13)"))
        item = self.tableWidget.item(4, 8)
        item.setText(_translate("MainWindow", "45(R37)"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("MainWindow", "26"))
        item = self.tableWidget.item(5, 6)
        item.setText(_translate("MainWindow", "36(R14R15)"))
        item = self.tableWidget.item(5, 8)
        item.setText(_translate("MainWindow", "46(R38)"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("MainWindow", "27"))
        item = self.tableWidget.item(6, 6)
        item.setText(_translate("MainWindow", "37(R16-21)"))
        item = self.tableWidget.item(6, 8)
        item.setText(_translate("MainWindow", "47(R39)"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget.item(7, 4)
        item.setText(_translate("MainWindow", "28"))
        item = self.tableWidget.item(7, 6)
        item.setText(_translate("MainWindow", "38(R23R25)"))
        item = self.tableWidget.item(7, 8)
        item.setText(_translate("MainWindow", "48(R40)"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableWidget.item(8, 4)
        item.setText(_translate("MainWindow", "29"))
        item = self.tableWidget.item(8, 6)
        item.setText(_translate("MainWindow", "39(R29R30)"))
        item = self.tableWidget.item(8, 8)
        item.setText(_translate("MainWindow", "49(R41)"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget.item(9, 4)
        item.setText(_translate("MainWindow", "30"))
        item = self.tableWidget.item(9, 6)
        item.setText(_translate("MainWindow", "40(R31)"))
        item = self.tableWidget.item(9, 8)
        item.setText(_translate("MainWindow", "50(日期)"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "姓名："))
        self.label_2.setText(_translate("MainWindow", "地区："))
        self.pushButton_add.setText(_translate("MainWindow", "录入"))
        self.pushButton_query.setText(_translate("MainWindow", "查询"))
        self.pushButton_delete.setText(_translate("MainWindow", "删除"))
        self.pushButton_export.setText(_translate("MainWindow", "导出"))
        self.pushButton_inport.setText(_translate("MainWindow", "导入"))

    def add_name_score(self):
        """添加成绩
        """
        # 获取姓名和地区
        name = self.textEditName.toPlainText()
        addr = self.textEditAddr.toPlainText()

        cur_score = {
            "name": name,
            "addr": addr,
            "value_list": [],
            "score": 0
        }
        # 获取分数
        value_list = self.get_cur_value()
        cur_score['value_list'] = value_list
        score = 0
        for i in range(len(value_list)):
            if value_list[i]:
                score += self.all_question_score(i+1)
        cur_score['score'] = score
        self.write_to_local_file(cur_score)
        myshow = MessageBox("添加成功")
        myshow.selectAbout()
        print("添加成功")
        self.reset_cur_value()

    def delete_name_score(self):
        """添加成绩
        """
        # 获取姓名和地区
        name = self.textEditName.toPlainText()
        addr = self.textEditAddr.toPlainText()

        key = "%s_%s" % (name, addr)
        self.delete_to_local_file(key)
        myshow = MessageBox("删除成功")
        myshow.selectAbout()
        print("删除成功")

    def query_name_score(self):
        """添加成绩
        """
        # 获取姓名和地区
        name = self.textEditName.toPlainText()
        addr = self.textEditAddr.toPlainText()

        key = "%s_%s" % (name, addr)
        all_dict = self.read_to_local_file()
        cur_value = all_dict.get(key)
        print(cur_value)
        if cur_value:
            self.set_cur_value(cur_value)
            myshow = MessageBox("查询成功")
            myshow.selectAbout()
            print("查询成功")
        else:
            myshow = MessageBox("不存在")
            myshow.selectAbout()
            print("不存在")

    def location(self):
        list_location = []
        for j in [1, 3, 5, 7, 9]:
            for i in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]:
                list_location.append([i, j])

        return list_location

    def get_cur_value(self):
        value_list = []
        list_location = self.location()
        for row, col in list_location:
            value_list.append(self.tableWidget.item(row, col).checkState())

        return value_list

    def reset_cur_value(self):
        list_location = self.location()
        for row, col in list_location:
            item = QtWidgets.QTableWidgetItem()
            item.setCheckState(QtCore.Qt.Checked)
            self.tableWidget.setItem(row, col, item)

    def set_cur_value(self, cur_value):
        list_location = self.location()
        value_list = cur_value['value_list']
        i = 0
        for row, col in list_location:
            item = QtWidgets.QTableWidgetItem()
            if value_list[i] == 0:
                item.setCheckState(QtCore.Qt.Unchecked)
            else:
                item.setCheckState(QtCore.Qt.Checked)
            self.tableWidget.setItem(row, col, item)
            i = i + 1

    def all_question_score(self, num):
        if num >= 1 and num <= 15:
            return 2
        elif num >= 16 and num <= 20:
            return 4
        elif num >= 21 and num <= 30:
            return 1
        elif num >= 31 and num <= 50:
            return 2

    def all_question_type(self, num):
        if num in [1, 2, 3, 17, 25, 31, 32, 50]:
            return "基本信息"
        elif num in [4, 5, 18, 22, 33]:
            return "经济及住房"
        elif num in [6, 7, 23, 34, 35, 36]:
            return "教育"
        elif num in [8, 9, 19, 24, 37]:
            return "就业扶贫"
        elif num in [10, 26, 38, 39]:
            return "社会保障"
        elif num in [11, 12, 27, 28, 40, 41, 42, 43, 44, 45]:
            return "医疗与康复"
        elif num in [13, 14, 46]:
            return "无障碍"
        elif num in [15, 20, 29, 30, 47, 48, 49]:
            return "文化体育"
        elif num in [16, 21]:
            return "工作流程"

    def write_to_local_file(self, cur_score):
        # 写入文件之前获取老数据
        if os.path.isfile("./data.json"):
            dict_all = self.read_to_local_file()
        else:
            dict_all = {}
        key = "%s_%s" % (cur_score['name'], cur_score['addr'])
        dict_all[key] = cur_score
        with open("./data.json", "w") as f:
            json.dump(dict_all, f)

    def read_to_local_file(self):
        if os.path.isfile("./data.json"):
            with open("./data.json", "r") as f:
                dict_all = json.load(f)
        else:
            dict_all = {}
        return dict_all

    def delete_to_local_file(self, key):
        dict_all = self.read_to_local_file()
        if dict_all:
            if key in dict_all.keys():
                dict_all.pop(key)
            with open("./data.json", "w") as f:
                json.dump(dict_all, f)

    def export_data(self):
        data = self.read_to_local_file()
        pwd = os.getcwd()

        with open("成绩单.csv", "w", newline='') as csvfile:
            writer = csv.writer(csvfile)
            body = [["试卷总数", "平均分", "姓名", "地区", "分数"]]
            all_num = len(data.keys())
            if not all_num:
                myshow = MessageBox("没有录入成绩单！请录入成绩单")
                myshow.selectAbout()
                return
            all_count = 0
            for key, value in data.items():
                all_count += value['score']
            avg_score = round(all_count/all_num, 2)

            for key, value in data.items():
                body.append([
                    all_num,
                    avg_score,
                    value['name'],
                    value['addr'],
                    value['score']
                ])
            # 写入多行用writerows
            writer.writerows(body)

        score_dir = os.path.join(os.path.abspath(pwd), "成绩单.csv")

        with open("模块分析.csv", "w", newline='') as csvfile:
            writer = csv.writer(csvfile)
            body = [["模块名", "总分", "平均分"]]
            all_num = len(data.keys())
            dict_model = {}

            for i in range(50):
                model_name = self.all_question_type(i+1)
                model_point = self.all_question_score(i+1)
                if model_name not in dict_model.keys():
                    dict_model[model_name] = model_point
                else:
                    dict_model[model_name] += model_point

            dict_point = {}
            for key, value in data.items():
                value_list = value['value_list']
                for i in range(50):
                    if value_list[i] == 2:
                        model_name = self.all_question_type(i + 1)
                        model_point = self.all_question_score(i + 1)
                        if model_name not in dict_point.keys():
                            dict_point[model_name] = model_point
                        else:
                            dict_point[model_name] += model_point

            for key, value in dict_model.items():
                body.append([
                    key,
                    value,
                    round(dict_point.get(key, 0)/all_num, 2)
                ])
            # 写入多行用writerows
            writer.writerows(body)

        model_dir = os.path.join(os.path.abspath(pwd), "模块分析.csv")

        with open("试题分析.csv", "w", newline='') as csvfile:
            writer = csv.writer(csvfile)
            body = [["题号", "答错人数", "错误率"]]
            all_num = len(data.keys())
            dict_error = {}
            for key, value in data.items():
                value_list = value['value_list']
                for i in range(50):
                    question_name = "第%s题" % str(i + 1)
                    if question_name not in dict_error.keys():
                        dict_error[question_name] = 0
                    if value_list[i] == 0:
                        dict_error[question_name] += 1

            for i in range(50):
                question_name = "第%s题" % str(i + 1)
                value = dict_error.get(question_name)
                body.append([
                    question_name,
                    value,
                    round(value/all_num, 2)
                ])
            # 写入多行用writerows
            writer.writerows(body)

        question_dir = os.path.join(os.path.abspath(pwd), "试题分析.csv")

        myshow = MessageBox('''导出成功:
        %s
        %s
        %s''' % (score_dir, model_dir, question_dir))

        myshow.selectAbout()


class MessageBox(QtWidgets.QWidget):
    def __init__(self, content):
        super(MessageBox, self).__init__()
        # self.initUi()
        self.content = content
    #
    # def initUi(self):
    #     self.setWindowTitle("MessageBox")
    #     self.setGeometry(400, 400, 300, 290)

    def selectAbout(self):
        QtWidgets.QMessageBox.about(self, "操作结果", self.content)
